default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dungeon_crawler_development

test:
  <<: *default
  database: dungeon_crawler_test

production:
  <<: *default
  database: dungeon_crawler_production
